# Generated by Django 5.2.17 on 2026-09-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enw', models.CharField(help_text='Enwiro environment name', max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.model')),
                ('workload_runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workloadrunner')),
            ],
        ),
    ]
