# Generated by Django 5.2.17 on 2026-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workloadrunner_model_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='enw',
            field=models.CharField(help_text='Enwiro environment name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workloadrunner',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='model',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='unique_model_name_per_provider'),
        ),
    ]
